# Generated by Django 5.0.1 on 2024-03-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='take_shot',
            field=models.TimeField(null=True),
        ),
    ]
