# Generated by Django 5.0.1 on 2024-02-02 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("process", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=10)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable",
                        to="process.camera",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "section")},
            },
        ),
        migrations.CreateModel(
            name="Thursday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("period", models.IntegerField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thursday",
                        to="reportings.timetable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Saturday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("period", models.IntegerField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saturday",
                        to="reportings.timetable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Monday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("period", models.IntegerField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monday",
                        to="reportings.timetable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("period", models.IntegerField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friday",
                        to="reportings.timetable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tuesday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("period", models.IntegerField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuesday",
                        to="reportings.timetable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wednesday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("period", models.IntegerField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wednesday",
                        to="reportings.timetable",
                    ),
                ),
            ],
        ),
    ]
