# Generated by Django 5.0.1 on 2024-02-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friday',
            name='course',
            field=models.CharField(default='Btech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friday',
            name='section',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday',
            name='course',
            field=models.CharField(default='btech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday',
            name='section',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saturday',
            name='course',
            field=models.CharField(default='btech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saturday',
            name='section',
            field=models.CharField(default='e', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thursday',
            name='course',
            field=models.CharField(default='btech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thursday',
            name='section',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuesday',
            name='course',
            field=models.CharField(default='btech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuesday',
            name='section',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wednesday',
            name='course',
            field=models.CharField(default='btech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wednesday',
            name='section',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='section',
        ),
    ]
