# Generated by Django 5.0.1 on 2024-02-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0002_alter_timetable_unique_together_friday_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='friday',
            name='section',
        ),
        migrations.RemoveField(
            model_name='monday',
            name='section',
        ),
        migrations.RemoveField(
            model_name='saturday',
            name='section',
        ),
        migrations.RemoveField(
            model_name='thursday',
            name='section',
        ),
        migrations.RemoveField(
            model_name='tuesday',
            name='section',
        ),
        migrations.RemoveField(
            model_name='wednesday',
            name='section',
        ),
        migrations.AlterField(
            model_name='friday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friday', to='reportings.class'),
        ),
        migrations.AlterField(
            model_name='monday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monday', to='reportings.class'),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saturday', to='reportings.class'),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thursday', to='reportings.class'),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuesday', to='reportings.class'),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wednesday', to='reportings.class'),
        ),
    ]
