# Generated by Django 5.0.1 on 2024-02-02 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0003_class_remove_friday_section_remove_monday_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friday',
            name='course',
        ),
        migrations.RemoveField(
            model_name='monday',
            name='course',
        ),
        migrations.RemoveField(
            model_name='saturday',
            name='course',
        ),
        migrations.RemoveField(
            model_name='thursday',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tuesday',
            name='course',
        ),
        migrations.RemoveField(
            model_name='wednesday',
            name='course',
        ),
        migrations.AddField(
            model_name='friday',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friday', to='reportings.class'),
        ),
        migrations.AddField(
            model_name='monday',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monday', to='reportings.class'),
        ),
        migrations.AddField(
            model_name='saturday',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saturday', to='reportings.class'),
        ),
        migrations.AddField(
            model_name='thursday',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thursday', to='reportings.class'),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tuesday', to='reportings.class'),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wednesday', to='reportings.class'),
        ),
    ]
