# Generated by Django 5.0.1 on 2024-02-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0004_remove_friday_course_remove_monday_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friday',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='monday',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='saturday',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='thursday',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='tuesday',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='wednesday',
            name='class_name',
        ),
    ]
