# Generated by Django 5.0.2 on 2024-02-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0006_friday_class_name_monday_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetable',
            name='room_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
