# Generated by Django 5.0.1 on 2024-03-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0009_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monday',
            name='teacher',
        ),
    ]
