# Generated by Django 5.0.1 on 2024-03-27 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0010_remove_monday_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='monday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportings.branch'),
        ),
    ]
