# Generated by Django 5.0.1 on 2024-03-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0011_monday_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friday',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='saturday',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='thursday',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='tuesday',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='wednesday',
            name='teacher',
        ),
    ]
