# Generated by Django 5.0.1 on 2024-03-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0012_remove_friday_teacher_remove_saturday_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportings.branch'),
        ),
        migrations.AddField(
            model_name='saturday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportings.branch'),
        ),
        migrations.AddField(
            model_name='thursday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportings.branch'),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportings.branch'),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportings.branch'),
        ),
    ]
