# Generated by Django 5.0.1 on 2024-03-27 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0015_alter_friday_teacher_alter_monday_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reportings.teacher'),
        ),
        migrations.AlterField(
            model_name='monday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reportings.teacher'),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reportings.teacher'),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reportings.teacher'),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reportings.teacher'),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reportings.teacher'),
        ),
    ]
